# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

variables:
- group : New variable
- group : demo

pool:
  vmImage: windows-2019

steps:
- task: Maven@1
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
    


- task: CopyFiles@2
  inputs:
    targetFolder: '$(Build.ArtifactStagingDirectory)'    

- task: ArchiveFilesWithEncryption@2
  inputs:
    Source: '$(Build.ArtifactStagingDirectory)'
    Dest: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    Encryption: 'hello'
- task: ExtractFilesWithEncryption@1
  inputs:
    Source: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    Dest: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)'
    Encryption: 'hello'
 
- task: PublishBuildArtifacts@1    
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    publishLocation: Container